// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using library_be.Data;

#nullable disable

namespace library_be.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240518100326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("library_be.Models.HistoryPeminjaman", b =>
                {
                    b.Property<long>("IDHISTORY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IDHISTORY"));

                    b.Property<long>("IDBUKU")
                        .HasColumnType("bigint");

                    b.Property<long?>("IDTRANSAKSI")
                        .HasColumnType("bigint");

                    b.Property<int>("LAMAPINJAM")
                        .HasColumnType("int");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TANGGALKEMBALI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TANGGALPINJAM")
                        .HasColumnType("datetime2");

                    b.HasKey("IDHISTORY");

                    b.HasIndex("IDBUKU");

                    b.HasIndex("IDTRANSAKSI");

                    b.HasIndex("NIM");

                    b.ToTable("Historypeminjaman");
                });

            modelBuilder.Entity("library_be.Models.InventoryBuku", b =>
                {
                    b.Property<long>("IDSTOK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IDSTOK"));

                    b.Property<long>("IDBUKU")
                        .HasColumnType("bigint");

                    b.Property<int>("JUMLAHSTOK")
                        .HasColumnType("int");

                    b.Property<string>("LOKASIRAK")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IDSTOK");

                    b.HasIndex("IDBUKU");

                    b.ToTable("Inventorybuku");
                });

            modelBuilder.Entity("library_be.Models.MasterBuku", b =>
                {
                    b.Property<long>("IDBUKU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IDBUKU"));

                    b.Property<string>("JUDUL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PENERBIT")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PENGARANG")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TAHUNTERBIT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDBUKU");

                    b.ToTable("Masterbuku");
                });

            modelBuilder.Entity("library_be.Models.MasterMahasiswa", b =>
                {
                    b.Property<string>("NIM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FAKULTAS")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JURUSAN")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("NIM");

                    b.ToTable("Mastermahasiswa");
                });

            modelBuilder.Entity("library_be.Models.TransaksiPeminjaman", b =>
                {
                    b.Property<long>("IDTRANSAKSI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IDTRANSAKSI"));

                    b.Property<string>("IDBUKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TANGGALKEMBALI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TANGGALPINJAM")
                        .HasColumnType("datetime2");

                    b.HasKey("IDTRANSAKSI");

                    b.HasIndex("NIM");

                    b.ToTable("Transaksipeminjaman");
                });

            modelBuilder.Entity("library_be.Models.HistoryPeminjaman", b =>
                {
                    b.HasOne("library_be.Models.MasterBuku", "MasterBuku")
                        .WithMany("HistoryPeminjaman")
                        .HasForeignKey("IDBUKU")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("library_be.Models.TransaksiPeminjaman", "TransaksiPeminjaman")
                        .WithMany("HistoryPeminjaman")
                        .HasForeignKey("IDTRANSAKSI")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("library_be.Models.MasterMahasiswa", "MasterMahasiswa")
                        .WithMany("HistoryPeminjaman")
                        .HasForeignKey("NIM")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MasterBuku");

                    b.Navigation("MasterMahasiswa");

                    b.Navigation("TransaksiPeminjaman");
                });

            modelBuilder.Entity("library_be.Models.InventoryBuku", b =>
                {
                    b.HasOne("library_be.Models.MasterBuku", "MasterBuku")
                        .WithMany("InventoryBuku")
                        .HasForeignKey("IDBUKU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterBuku");
                });

            modelBuilder.Entity("library_be.Models.TransaksiPeminjaman", b =>
                {
                    b.HasOne("library_be.Models.MasterMahasiswa", "MasterMahasiswa")
                        .WithMany("TransaksiPeminjaman")
                        .HasForeignKey("NIM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterMahasiswa");
                });

            modelBuilder.Entity("library_be.Models.MasterBuku", b =>
                {
                    b.Navigation("HistoryPeminjaman");

                    b.Navigation("InventoryBuku");
                });

            modelBuilder.Entity("library_be.Models.MasterMahasiswa", b =>
                {
                    b.Navigation("HistoryPeminjaman");

                    b.Navigation("TransaksiPeminjaman");
                });

            modelBuilder.Entity("library_be.Models.TransaksiPeminjaman", b =>
                {
                    b.Navigation("HistoryPeminjaman");
                });
#pragma warning restore 612, 618
        }
    }
}
